name: Build and Deploy Barcelona Project

on:
  push:
    branches:
      - main  # Or your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'  

    - name: Create .env file
      run: |
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo URL_NEXT_GAME=${{ secrets.URL_NEXT_GAME }} >> .env
        echo URL_LAST_GAME=${{ secrets.URL_LAST_GAME }} >> .env
        echo URL_STANDINGS=${{ secrets.URL_STANDINGS }} >> .env
        echo API_KEY_NEWS=${{ secrets.API_KEY_NEWS }} >> .env
        echo URL_NEWS=${{ secrets.URL_NEWS }} >> .env

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

